version: '3'

services:
    backend:
        restart: unless-stopped
        build:
            context: ./backend
            dockerfile: Dockerfile.prod
        command: sh -c "mkdir -p gunicorn_logs && gunicorn cdcrc_website.wsgi:application --workers=8 --bind 0.0.0.0:8000 --error-logfile gunicorn_logs/error.log --access-logfile gunicorn_logs/access.log --log-level debug --capture-output"
        env_file:
            - ./.env
        # ***for testing only
        # ports:
        #     - 2587:8000
        environment:
            - PYTHONUNBUFFERED=TRUE
            - DEBUG=0
        volumes:
            - static_webassets:/backend/static_cdn/
            - media_webassets:/backend/media/
            - './gunicorn_logs/:/backend/gunicorn_logs/'
        depends_on:
            - postgres_db

    nginx:
        restart: unless-stopped
        build:
            context: ./nginx
            dockerfile: Dockerfile.prod
        # Mapping Container PORT 80 to Host PORT 5000
        ports:
            - 80:80
            - 443:443
            # ***for testing only
            # - 8000:80
        depends_on:
            - backend
        volumes:
            - static_webassets:/static/
            - media_webassets:/media/
            - /etc/letsencrypt/live/cdcrc.iitrpr.ac.in/:/certs/iitrpr.ac.in/

    postgres_db:
        restart: unless-stopped
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env

volumes:
    static_webassets:
    postgres_data:
    media_webassets:

